### ISSUE TITLE
[BUG] Managed Config Setting "disableNewParentAccount" not functioning

### ISSUE THREAD

**Issue by justinkumpe** [kumpeapps/KKid#58]
**Describe the bug**
Managed Config Setting "disableNewParentAccount" not functioning. When setting is set to true the new parent account button is still present

**Expected behavior**
When disableNewParentAccount is set to true the New Parent Account button should not function

**Comment by KumpeApps-API** [comment]
<p>Helpdesk Ticket Closed via Automation due to linked GitHub issue was closed. GitHub issue will be locked to prevent re-opening. If you are still experiencing this issue please raise a new issue.</p>
