### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by justinkumpe** [kumpeapps/KKid#61]
TMDb linking not working after newest release.

**Comment by justinkumpe** [comment]
Issue was due to mis-configuration on the API server. Issue has been resolved.

**Comment by KumpeApps-API** [comment]
<p>Helpdesk Ticket Closed via Automation due to linked GitHub issue was closed. GitHub issue will be locked to prevent re-opening. If you are still experiencing this issue please raise a new issue.</p>
