### ISSUE TITLE
[BUG] Chore Count not updating

### ISSUE THREAD

**Issue by justinkumpe** [kumpeapps/KKid#62]
Reported by Helpdesk ticket

Chore count is not updating when new chores are added or existing chores are completed.

**Comment by KumpeApps-API** [comment]
<p>Resolved issue with API server causing push notifications to not be sent correctly. This issue should now be resolved</p><p>Thanks<br />
Justin Kumpe<br />
KumpeApps LLC</p>

**Comment by KumpeApps-API** [comment]
<p>Helpdesk Ticket Closed via Automation due to linked GitHub issue was closed. GitHub issue will be locked to prevent re-opening. If you are still experiencing this issue please raise a new issue.</p>
