### ISSUE TITLE
[BUG] Haptic feedback not working on iPhone 14 Pro

### ISSUE THREAD

**Issue by justinkumpe** [kumpeapps/KKid#83]
**Describe the bug**
Haptic feedback not working on iPhone 14 Pro

**Smartphone (please complete the following information):**
-   Device: iPhone 14 Pro
-   OS: 16.0.2

**Comment by justinkumpe** [comment]
Issue has been identified with Haptico Pluggin. Submitted Pull Request iSapozhnik/Haptico#17 to resolve issue. This issue will be resolved in the next KKid release

**Comment by iSapozhnik** [comment]
The new version of Haptico should be already available.

```
 🎉  Congrats

 🚀  Haptico (1.2.0) successfully published
 📅  November 17th, 00:30
 🌎  https://cocoapods.org/pods/Haptico
 👍  Tell your friends!
```

**Comment by justinkumpe** [comment]
Thanks
